ACTIVE_PROFILE: prod

PRIVATE_KEY: "private.key"
PUBLIC_KEY: "public.key"
POSTGRES_USERNAME: user
POSTGRES_PASSWORD: 0000
POSTGRES_DATABASE: db_name
POSTGRES_HOST: 127.168.1.209
POSTGRES_PORT: 5432

USER_NAME: admin
PASSWORD: 0000

SERVER_PORT: 9090
UI_APP_URL: https://localhost:9090
